#107 Add the posibility to display the "ReqIF.Text" attribute of Requirement elements in Capella Richtext editor
eclipse/capella-requirements-vp pull request #108
Opened 2021-01-08 11:51 UTC by minhtutonthat

Resolves #107

Change-Id: Ie75a86317b6ddcc53da7047839e4a1be99de06c7
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>

2021-01-11 14:55 UTC, pdulth requested changes

2021-01-11 14:55 UTC, pdulth commented on plugins/org.polarsys.capella.vp.requirements.importer/src/org/polarsys/capella/vp/requirements/importer/transposer/bridge/ImageImporter.java
> +  public ImageImportStrategy getImgImportStragety() {
ImportStrategy

2021-01-11 14:55 UTC, pdulth commented on plugins/org.polarsys.capella.vp.requirements.importer/src/org/polarsys/capella/vp/requirements/importer/transposer/bridge/ImageImporter.java
> +  public void setImgImportStragety(ImageImportStrategy imgImportStragety) {
ImportStrategy

2021-01-11 14:55 UTC, pdulth commented on plugins/org.polarsys.capella.vp.requirements.importer/src/org/polarsys/capella/vp/requirements/importer/transposer/bridge/ImageImportStrategy.java
> +public enum ImageImportStrategy {
ImportStrategy

2021-01-11 14:55 UTC, pdulth commented on plugins/org.polarsys.capella.vp.requirements.importer/src/org/polarsys/capella/vp/requirements/importer/transposer/bridge/ImageImportingDialog.java
> +  private static final String DEFAULT_MESSAGE = "The imported ReqIf file references images. Please indicate below how to import these images into your model.\n";
can you externalize string to messages?

2021-01-11 16:27 UTC, minhtutonthat commented on plugins/org.polarsys.capella.vp.requirements.importer/src/org/polarsys/capella/vp/requirements/importer/transposer/bridge/ImageImporter.java
> +  public ImageImportStrategy getImgImportStragety() {
Nice catch :)

2021-01-12 11:07 UTC, pdulth approved these changes

2021-01-12 11:07 UTC, merged