#130 Add QuickFix for VR REQ_Relation_01, REQ_Relation_02
eclipse/capella-requirements-vp pull request #131
Opened 2021-05-07 14:03 UTC by georgiana-ecobici

Resolves #130

Change-Id: I0dd6502fd052ea53a6ca78ecefc2212fbbb8ee0a
Signed-off-by: Georgiana-Elena ECOBICI <georgiana-elena.ecobici@thalesgroup.com>

2021-05-10 08:12 UTC, MalinaStefaniaStoicanescu approved these changes

2021-05-11 11:54 UTC, pdulth requested changes

2021-05-11 11:54 UTC, pdulth commented on plugins/org.polarsys.capella.vp.requirements.quickfix/META-INF/MANIFEST.MF
> +Bundle-Vendor: %bundleVendor
%bundleVendor or %providerName

https://github.com/eclipse/capella-requirements-vp/pull/131/files#diff-d2669dcea6057ed13c8697433d989ab21e0ab34582e9cd5ee6e97456d2fa5b41R14

2021-05-11 11:54 UTC, pdulth commented on plugins/org.polarsys.capella.vp.requirements.quickfix/plugin.properties
> +providerName = Eclipse.org
shall be the same as abpve %bundleVendor or %providerName

2021-05-18 06:15 UTC, pdulth approved these changes

2021-05-18 06:16 UTC, merged