#132 Migrate doc to mediawiki
eclipse/capella-requirements-vp pull request #133
Opened 2021-05-10 07:40 UTC by MalinaStefaniaStoicanescu

Change-Id: I0965a2cd5a847b2f112f63291a6d81bbda31a899
Signed-off-by: MalinaStefaniaStoicanescu <malina.stoicanescu@thalesgroup.com>

2021-05-10 09:42 UTC, claudiasima-ro approved these changes

2021-05-11 12:31 UTC, pdulth requested changes
- Can you remove the root pages 2_programmerguide.mediawiki  3_userguide.mediawiki 4_limitations_knownissues.mediawiki

They contains a Table of Content manually created which is source of inconsistencies and links doesn't work when we look at online version 
https://github.com/eclipse/capella-requirements-vp/blob/8f418cb6684e1cb9dc0039bbdf3deac5bd07ef41/plugins/org.polarsys.capella.vp.requirements.doc/html/4_knownissues/4_limitations_knownissues.mediawiki 

In https://github.com/MalinaStefaniaStoicanescu/capella-requirements-vp/blob/mastercx/plugins/org.polarsys.capella.vp.requirements.doc/toc/index.xml, if you remove the href reference towards those pages, eclipse will generate dynamically those page.


- The link Requirement Vewpoint Guide > Programmer's Guide > Extension Points >  org.polarsys.capella.vp.requirements.importer.extension.attributesProvider
doeesn't work on Left table of content, and in 23_extensionpoints.mediawiki page

![image](https://user-images.githubusercontent.com/34767327/117815305-9e2b2200-b265-11eb-81b0-d31f0dd2578b.png)

2021-05-11 12:42 UTC, pdulth requested changes
~~Can you also remove the known issues sections as it doesn't exist in any other addons~~
=> MELODY-9651

2021-05-12 13:55 UTC, georgiana-ecobici approved these changes

2021-05-17 07:38 UTC, pdulth requested changes
In the extension_point.png, can you remove Orchestra as this is not an opensource keyword..

2021-05-18 06:14 UTC, pdulth approved these changes

2021-05-18 06:15 UTC, merged