Master epl
eclipse/capella-requirements-vp pull request #16
Opened 2020-12-08 15:41 UTC by sandupostaru

2020-12-09 09:19 UTC, pdulth requested changes
Can you also update epl on feature.properties, and testSuite files.
Thanks

2020-12-09 09:24 UTC, sandupostaru commented
> 
> 
> Can you also update epl on feature.properties / plugin.properties, and testSuite files.
> Thanks

Good catch.
Will do.

2020-12-09 10:05 UTC, pdulth requested changes
Can you update also fields on this file to EPL 2
Those lines appears when you install addon via update site

2020-12-10 09:22 UTC, pdulth approved these changes

2020-12-10 09:22 UTC, merged